---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/
    - /bin/cp -R api css images js *.html metadata.json README.md $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/chmod 755 $DEPLOYPATH/api
    - /bin/chmod 644 $DEPLOYPATH/api/*.php
    - /bin/chmod 644 $DEPLOYPATH/.htaccess
